config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#home"
  devise_for :users
  resources :users, only: :show
  get "/data", to: "data#choose_data"
  post "/data", to: "data#display_data"
  get "/learn", to: "data#learn"
  get "/action", to: "data#action"

end

app/views/layouts/_flash.html.erb
<div class="flash-notice text-center">
  <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/layouts/_red_panda.html.erb
<header class="header">
<h1 class="main-header">Impact</h1>
</header>

app/views/layouts/_top_bar.html.erb
<div class="top-bar" id="main-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><%= link_to image_tag("impact-logo.png"), root_path %></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><%= link_to "Create", data_path %></li>
      <li><%= link_to "Learn", learn_path %></li>
      <li><%= link_to "Take Action", "#" %></li>
      <li class="divider"></li>
      <li><%= link_to "About", root_path %><li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Impact" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Lato:700|Signika' rel='stylesheet' type='text/css'>
    <!-- <script src="http://code.highcharts.com/modules/exporting.js"></script>
    <script src="http://code.highcharts.com/modules/offline-exporting.js"></script> -->
  </head>

  <body>
    <%= render "layouts/top_bar" %>
    <%= render "layouts/red_panda" %>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>